"""fix blog content column

Revision ID: d0ca517c0e2c
Revises: 13cfbe9b0010
Create Date: 2025-09-24 10:56:38.446388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0ca517c0e2c'
down_revision = '13cfbe9b0010'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
